---
title: "Untitled"
author: "LEE EUNJI"
date: "2019년 5월 29일"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 시계열 자료 정리

# 데이터 불러오기
```{r warning=FALSE}
setwd("C:\\Users\\EUNJI\\Desktop\\ds_yonsei\\프로젝트\\data\\real")
final <- read.csv("final_0606.csv", header = TRUE)
library(tidyverse)
```


## 치킨 데이터 만들기  

```{r}
ts_data_chicken <- its_eats %>%
  filter(type == "치킨" & region == "강서구") %>%
  select(date, gangsu, rain, temperature, holiday.y, KBO, soccer)
ts_data_chicken <- unique(ts_data_chicken)

calls_chicken <- its_eats %>%
  filter(type == "치킨" & region == "강서구") %>%
  select(date, call) %>%
  group_by(date) %>%
  summarise(calls = sum(call))

ts_data_chicken <- left_join(calls_chicken, ts_data_chicken, by = "date")
ts_data_chicken <- ts(ts_data_chicken)
```




## 시계열 모델 작성

```{r}
ts.plot(ts_data_chicken[,"calls"])
par(mfrow=c(1,2))
acf(ts_data_chicken[,"calls"],main="ACF",lag=50)
pacf(ts_data_chicken[,"calls"],main="PACF",lag=50)
```


```{r}
diff_calls_chi <- diff(ts_data_chicken[,"calls"], lag =7) 
acf(diff_calls_chi,main="ACF",lag=35)
pacf(diff_calls_chi,main="PACF",lag=35)
```
<계절성> -> ARMA(1,2)
ACF:2에서 지수적 감소  PACF: 3에서 지수적 감소
<계절X> -> 2에서 절단 / 1에서 지수적 감소 


# 후보모형 작성

```{r}
library(forecast)
covariate <- c("gangsu","rain","temperature","holiday.y","KBO","soccer")
fit1 <- auto.arima(ts_data_chicken[,"calls"], xreg = ts_data_chicken[,covariate])
fit2 <- arima(ts_data_chicken[,"calls"], xreg = ts_data_chicken[,covariate], order = c(5,1,2),
              seasonal = list(order=c(0,0,2), period =7))
fit3 <- arima(ts_data_chicken[,"calls"], xreg = ts_data_chicken[,covariate], order = c(1,0,1),
              seasonal = list(order=c(0,0,2), period =7))
fit4 <- arima(ts_data_chicken[,"calls"], xreg = ts_data_chicken[,covariate], order = c(5,1,2),
              seasonal = list(order=c(1,0,2), period =7))
fit5 <- arima(ts_data_chicken[,"calls"], xreg = ts_data_chicken[,covariate], order = c(1,0,1),
              seasonal = list(order=c(1,0,1), period =7))
fit2$arma
fit1$arma
```


# aic 비교
```{r}
c(fit1$aic, fit2$aic, fit3$aic, fit4$aic, fit5$aic)
```

aic가 가장 작은 4번 모형 선택

## 예측

```{r}
fit4
checkresiduals(fit4)
pred <- forecast(fit2, xreg = ts_data_chicken[,covariate])
```

## 비교 그래프 그리기
```{r}
plot(ts_data_chicken[,"calls"])
lines(fitted(pred), col = "blue")
text("MAE=",caret::MAE(ts_data_chicken[,"calls"],pred$fitted))
lines(pred_chicken$mean, col ="blue")
calls_chicken <- ts_data_chicken[,"calls"]
caret::RMSE(calls_chicken$calls, pred$fitted)
caret::MAE(calls_chicken$calls,pred$fitted)
```



## 피자 데이터 만들기  

```{r}
ts_data_pizza <- final %>%
  filter(type == "피자" & region == "강남구") %>%
  select(date, gangsu, rain, temperature, holiday.y, KBO, soccer)
ts_data_pizza <- unique(ts_data_pizza)

calls_pizza <- final %>%
  filter(type == "피자" & region == "강남구") %>%
  select(date, call) %>%
  group_by(date) %>%
  summarise(calls = sum(call))

ts_data_pizza <- left_join(calls_pizza, ts_data_pizza, by = "date")
ts_data_pizza <- ts(ts_data_pizza)
```




## 시계열 모델 작성

```{r}
ts.plot(ts_data_pizza[,"calls"])
par(mfrow=c(1,2))
acf(ts_data_pizza[,"calls"],main="ACF",lag=50)
pacf(ts_data_pizza[,"calls"],main="PACF",lag=50)
```


```{r}
diff_calls_pi <- diff(ts_data_pizza[,"calls"], lag =7) 
acf(diff_calls_pi,main="ACF",lag=35)
pacf(diff_calls_pi,main="PACF",lag=35)
```
<계절성> -> ARMA(0,2)
ACF:1에서 지수적 감소  PACF: 3에서 지수적 감소
<계절X> -> 1에서 절단 / 1에서 지수적 감소 


# 후보모형 작성

```{r}
library(forecast)
covariate <- c("gangsu","rain","temperature","holiday.y","KBO","soccer")
fit1 <- auto.arima(ts_data_pizza[,"calls"], xreg = ts_data_pizza[,covariate])
fit2 <- arima(ts_data_pizza[,"calls"], xreg = ts_data_pizza[,covariate], order = c(2,1,2),
              seasonal = list(order=c(0,0,2), period =7))
fit3 <- arima(ts_data_pizza[,"calls"], xreg = ts_data_pizza[,covariate], order = c(1,0,1),
              seasonal = list(order=c(0,0,2), period =7))
fit4 <- arima(ts_data_pizza[,"calls"], xreg = ts_data_pizza[,covariate], order = c(2,1,2),
              seasonal = list(order=c(1,0,2), period =7))
fit5 <- arima(ts_data_pizza[,"calls"], xreg = ts_data_pizza[,covariate], order = c(1,0,1),
              seasonal = list(order=c(1,0,2), period =7))
```


# aic 비교
```{r}
c(fit1$aic, fit2$aic, fit3$aic, fit4$aic, fit5$aic)
```

aic가 가장 작은 4번 모형 선택

## 예측

```{r}
fit4
checkresiduals(fit4)
pred_pizza <- forecast(fit4, xreg = ts_data_pizza[,covariate])
```

## 비교 그래프 그리기
```{r}
par(mfrow=c(1,1))
plot(ts_data_pizza[,"calls"])
lines(fitted(pred_pizza), col = "blue")
lines(pred_pizza$mean, col ="blue")
calls_pizza<- ts_data_pizza[,"calls"]
caret::RMSE(calls_pizza, pred_pizza$fitted)
caret::MAE(calls_pizza,pred_pizza$fitted)
```




## 중국집 데이터 만들기  

```{r warning=FALSE}
ts_data_chinese <- final %>%
  filter(type == "중국집" & region == "강남구") %>%
  select(date, gangsu, rain, temperature, holiday.y, KBO, soccer)
ts_data_chinese <- unique(ts_data_chinese)

calls_chinese <- final %>%
  filter(type == "중국집" & region == "강남구") %>%
  select(date, call) %>%
  group_by(date) %>%
  summarise(calls = sum(call))

ts_data_chinese <- left_join(calls_chinese, ts_data_chinese, by = "date")
ts_data_chinese <- ts(ts_data_chinese)
```




## 시계열 모델 작성

```{r warning=FALSE}
ts.plot(ts_data_chinese[,"calls"])
par(mfrow=c(1,2))
acf(ts_data_chinese[,"calls"],main="ACF",lag=50)
pacf(ts_data_chinese[,"calls"],main="PACF",lag=50)
```


```{r warning=FALSE}
diff_calls_chinese <- diff(ts_data_chinese[,"calls"], lag =7) 
acf(diff_calls_chinese,main="ACF",lag=35)
pacf(diff_calls_chinese,main="PACF",lag=35)
```
<계절성> -> SARMA(0,2)
ACF:3에서 지수적 감소  PACF: 3에서 지수적 감소
<계절X> -> 2에서 절단 / 1에서 지수적 감소 


# 후보모형 작성

```{r warning=FALSE}
library(forecast)
covariate <- c("gangsu","rain","temperature","holiday.y","KBO","soccer")
fit1 <- auto.arima(ts_data_chinese[,"calls"], xreg = ts_data_chinese[,covariate])
fit2 <- arima(ts_data_chinese[,"calls"], xreg = ts_data_chinese[,covariate], order = c(1,1,3),
              seasonal = list(order=c(2,0,2), period =7))
fit3 <- arima(ts_data_chinese[,"calls"], xreg = ts_data_chinese[,covariate], order = c(0,0,1),
              seasonal = list(order=c(2,0,2), period =7))
fit4 <- arima(ts_data_chinese[,"calls"], xreg = ts_data_chinese[,covariate], order = c(1,1,3),
              seasonal = list(order=c(1,0,2), period =7))
fit5 <- arima(ts_data_chinese[,"calls"], xreg = ts_data_chinese[,covariate], order = c(1,0,1),
              seasonal = list(order=c(1,0,2), period =7))
```


# aic 비교
```{r}
c(fit1$aic, fit2$aic, fit3$aic, fit4$aic, fit5$aic)
```

aic가 가장 작은 4번 모형 선택

## 예측

```{r warning=FALSE}
fit4
checkresiduals(fit4)
pred_chinese <- forecast(fit4, xreg = ts_data_chinese[,covariate])
```

## 비교 그래프 그리기
```{r warning=FALSE}
par(mfrow=c(1,1))
plot(ts_data_chinese[,"calls"])
lines(fitted(pred_chinese), col = "blue")
lines(pred_chinese$mean, col ="blue")
calls_chinese<- ts_data_chinese[,"calls"]
caret::RMSE(calls_chinese, pred_chinese$fitted)
caret::MAE(calls_chinese,pred_chinese$fitted)
```

